### ISSUE TITLE
Update VS Code read me skaffold modules example 

### ISSUE THREAD

**Issue by srithreepo** [GoogleCloudPlatform/cloud-code-samples#1019]
**Describe the bug**
Skaffold modules section of the Guestbook readme needs to be updated.  

**To Reproduce**
1. Download the Guestbook sample app on VScode. 
2. On the Readme, Click on Skaffold modules. 

**Expected behavior**
This section needs to be updated. 
**Current content**
> Now, you can quickly iterate on the frontend service without having to rebuild and deploy the entire app for every change.
> a. Navigate to [frontend/Views/Home/Index.cshtml](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/v1/nodejs/nodejs-guestbook/src/frontend/Views/Home/Index.cshtml).
> b. Make a change to the file (e.g. "My Guestbook" > "My Frontend Guestbook").
> c. The frontend service will rebuild and you can see your changes in the deployed frontend service.
> 
> You can see how the Guestbook frontend module is defined by checking out the frontend's [skaffold.yaml](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/v1/nodejs/nodejs-guestbook/src/frontend/skaffold.yaml) file.
> 

**New content**
> Now, you can quickly iterate on the frontend service without having to rebuild and deploy the entire app for every change.
> a. Navigate to [frontend/Views/home.pug](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/v1/nodejs/nodejs-guestbook/src/frontend/views/home.pug).
> b. Make a change to the file (e.g. "My Guestbook" > "My Frontend Guestbook").
> c. The frontend service will rebuild and you can see your changes in the deployed frontend service.
> 
> You can see how the Guestbook frontend module is defined by checking out the frontend's [skaffold.yaml](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/v1/nodejs/nodejs-guestbook/src/frontend/skaffold.yaml) file.
> 

**Screenshots**
![image](https://user-images.githubusercontent.com/17151014/167708142-2d47d175-11fd-4b32-a299-2b9e92045089.png)
![image](https://user-images.githubusercontent.com/17151014/167708153-9317ef7d-85ce-4eb9-a433-98f7d0070e3f.png)

** Template in use:**
 - Node.js
 - Cloud Code Node JS Guestbook app. 

**Cloud Code in use:**
 - Cloud Code for VS Code 1.18.1-insiders
 - Potentially applicable to other versions too

**Comment by kelsk** [comment]
@srithreepo Thanks for catching this!

**Comment by kelsk** [comment]
Fixed with #1022
