### ISSUE TITLE
vscode README references Clusters explorer instead of Kubernetes panel included with OAB update

### ISSUE THREAD

**Issue by fatoboist** [GoogleCloudPlatform/cloud-code-samples#1024]
**Describe the bug**
the vscode README.md is not up to date with OAB UI changes and references the **Clusters** explorer instead of the new **Kubernetes** section.

**Expected behavior**
README should reference new UI text.

** Template in use:**
 - Python
 - https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/python/python-hello-world 

**Cloud Code in use:**
 - [Cloud Code for VS Code] 
 - OS: Debian GNU/Linux rodete
 - Browser chrome
 - Version 101.0.4951.54

**Comment by ace-n** [comment]
[This](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/python/python-hello-world/.readmes/vscode) looks like the responsible file.

**Comment by ace-n** [comment]
@fatoboist are you referring to [this section](https://github.com/GoogleCloudPlatform/cloud-code-samples/tree/v1/python/python-hello-world/.readmes/vscode#:~:text=free%20local%20cluster.-,Navigate%20to%20the%20Clusters%20explorer%20in%20the%20Cloud%20Code%20%2D%20Kubernetes%20sidebar,-using%20the%20left) of the `README` files?

Based on the highlighted text, it seems like that's up-to-date.

**Comment by fatoboist** [comment]
Yes, that's the section.

It isn't up to date for VS Code (where Cloud Shell **!=** VS Code), as VS Code has moved to the one activity bar and now has a Kubernetes section instead of a clusters explorer. ref: https://cloud.google.com/code/docs/vscode/deploy-kubernetes-app#creating_a_cluster
