### ISSUE TITLE
[BUG] #1128

### ISSUE THREAD

**Issue by Mariano0808** [GoogleCloudPlatform/cloud-code-samples#1128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

** Template in use:**
 - Language
 - Path to template

**Cloud Code in use:**
 - [Cloud Code for VS Code] | [Cloud Code for IntelliJ]

**Additional context**

**Comment by Mariano0808** [comment]
#1128

**Comment by pattishin** [comment]
Hi @Mariano0808, if there is an issue that you've spotted in our repo - do please fill out the template you've added above. Closing this issue out for now.
