### ISSUE TITLE
Samples are broken for Cloud Code IntelliJ after update to vbeta16

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-samples#157]
CC IJ provides managed dependencies, and the latest schema supported by managed Skaffold is vbeta15, not 16. We are planning release for Oct 31st tentatively, need to revert the schema update back to `v1beta15` until it's in.

**Comment by simonz130** [comment]
I'll downgrade the schema to 15.

Is there a way we can test IntelliJ samples flow automatically?

**Comment by ivanporty** [comment]
Not yet unfortunately. Target Q4-Q1.

**Comment by ivanporty** [comment]
(for initial set of integration testing.)

**Comment by ivanporty** [comment]
@sageprice FYI, is there any option to test the samples against our latest managed dependencies versions of skaffold and kubectl? Maybe download and test samples with them?

**Comment by sageprice** [comment]
> @sageprice FYI, is there any option to test the samples against our latest managed dependencies versions of skaffold and kubectl? Maybe download and test samples with them?

AFAIK this would have to be done manually as you've described. If we want to test the samples against skaffold/kubectl versions newer than what we're using then we have to download the latest and specify their usage as custom dependencies in settings:
![custom-deps](https://user-images.githubusercontent.com/9577120/67589865-86458900-f727-11e9-8f54-695fcfe2e47c.png)

**Comment by simonz130** [comment]
How IntelliJ tests "Create new application" flow today? Is it done manually for each release?

**Comment by ivanporty** [comment]
Yes, it is manual. Each new release has a fixed version of `skaffold` bundled and used by Cloud Code managed dependencies component. It will be same for VS Code once they release managed dependencies. We test manually mostly now, but again, planning to get some integration coverage soon.

**Comment by simonz130** [comment]
Thanks Ivan. I'm closing the bug for now as the samples should not be broken at this point. We should discuss it further how to automate the testing.
