### ISSUE TITLE
Skaffold / jib issue with maven wrapper

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#168]
Using the latest java hello world sample, and attempting to deploy using Cloud Code IntelliJ, I'm seeing:

```
time="2019-11-04T17:21:45-05:00" level=warning msg="error checking cache, caching may not work as expected: getting hash for artifact java-hello-world: getting dependencies for java-hello-world: getting jib-maven dependencies: initial Jib dependency refresh failed: failed to get Jib dependencies: starting command &{/usr/local/google/home/eshaul/IdeaProjects/untitled209/mvnw [/usr/local/google/home/eshaul/IdeaProjects/untitled209/mvnw jib:_skaffold-fail-if-jib-out-of-date -Djib.requiredVersion=1.4.0 --non-recursive jib:_skaffold-files-v2 --quiet] [] . <nil> 0xc00075e0a0 0xc00075e0b0 [] <nil> <nil> <nil> 0xc000646440 <nil> false [0xc00075e0b8 0xc00075e0a0 0xc00075e0b0] [0xc00075e0a0 0xc00075e0b0 0xc00075e0b8] [0xc00075e098 0xc00075e0a8] [] <nil> <nil>}: fork/exec /usr/local/google/home/eshaul/IdeaProjects/untitled209/mvnw: permission denied"
time="2019-11-04T17:21:45-05:00" level=fatal msg="exiting dev mode because first build failed: build failed: build failed: building [java-hello-world]: build artifact: maven build failed: fork/exec /usr/local/google/home/eshaul/IdeaProjects/untitled209/mvnw: permission denied"
```

@ivanporty seems related to https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/154 . When I delete the maven wrapper, it starts to work

**Comment by ivanporty** [comment]
Is this for templates? What if you open an example from the samples directory directly, not using IDE checkout? How about guestbook? Is `mvnw` marked executable when checked out as part of templates?

**Comment by etanshaul** [comment]
> Is this for templates?

Yeah this is for the Cloud Code java hello-world template (that's why I filed this on the cloud-code-samples repo).

> What if you open an example from the samples directory directly, not using IDE checkout? How about guestbook? Is mvnw marked executable when checked out as part of templates?

Will update

**Comment by etanshaul** [comment]
> Is mvnw marked executable when checked out as part of templates?

This is the issue - good call. Its not executable when checked out. I'll narrow down to see if its cloud code's checkout process specifically, or not.

**Comment by etanshaul** [comment]
when checking out manually it works.

Something in the IntelliJ wizard checkout logic is not preserving the executable state of files. Will migrate issue. thanks @ivanporty
