### ISSUE TITLE
Use DNS instead IP address when connecting to Mongo

### ISSUE THREAD

**Issue by mtwo** [GoogleCloudPlatform/cloud-code-samples#21]
Related to #8 ... rather than reading an IP address from an environment variable, the backend could connect to the Mongo database via its hostname: "mongo-service". This should allow Mongo to automatically reconnect if the Mongo pod gets a new IP address.

I've tested this in my own project and it appears to fix the startup issues that we had to use an initContainer for, and should generally make the app more robust.

**Comment by mtwo** [comment]
@simonz130

**Comment by mtwo** [comment]
@ahmetb @simonz130 

Should I create a PR with my code? It works consistently even with the initContainer removed

**Comment by ahmetb** [comment]
Let’s wait for @murog’s fixes to get in. Ideally #22 should be the fix for env variables —it shouldn’t assume defaults to be consistent.

**Comment by mtwo** [comment]
I've verified that this change also causes the backend service to reconnect to the database after the database pod is restarted

**Comment by simonz130** [comment]
Morgan, can you sync to latest and verify that it's fixed?

**Comment by simonz130** [comment]
@mtwo

**Comment by mtwo** [comment]
The latest code still reads in the database IP address from an environment variable ... if I kill the database pod and it gets a new IP, the backend will still be trying to use the old IP and will fail. Or am I missing something?

**Comment by simonz130** [comment]
Did you pull latest version, re-build the images and re-deploy?
This is the latest code:
https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/nodejs/nodejs-guestbook/kubernetes-manifests/guestbook-backend.deployment.yaml
Address of the DB is read from environment variable that is defined with name.
