### ISSUE TITLE
[BUG] Add Compound Launch Configurations for VS Code in launch.json for Guestbook samples 

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#249]
**Describe the bug**
Users can currently only select to debug frontend or backend from a launch config. With a compound, they can debug the whole application with a config entry point. 

**To Reproduce**
1) Open VS Code with Cloud Code installed
2) Select New Application > Node JS Guestbook (or any language)
3) Switch to the Run and Debug view in the Activity Bar
4) Select the dropdown

**Expected behavior**
An option to debug all the services in the application. 

**Actual behavior**
Options to debug individual services in the application

**Screenshots**
![image](https://user-images.githubusercontent.com/1621731/77119160-22cc3880-69f3-11ea-8b48-5ecfa9b97401.png)

**Template in use:**
 - Any language Guestbook, e.g. https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/nodejs/nodejs-guestbook/.vscode/launch.json

**Cloud Code in use:**
 - Cloud Code for VS Code
 - OS: OSX 
 - Version: 1.20

**Additional context**
This can be solved by using compounds in the launch configuration: https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations

**Comment by j-windsor** [comment]
Now that we are using skaffold debug, this is no longer an issue.
