### ISSUE TITLE
[BUG] Cloud Run Java Sample has failing tests

### ISSUE THREAD

**Issue by fsladkey** [GoogleCloudPlatform/cloud-code-samples#255]
**Describe the bug**
Cloud Run Java Sample has failing tests

**To Reproduce**
1. Open Cloud Run Java Sample
2. Run ./mvnw test
4. Tests fail

**Expected behavior**
Tests pass!

** Template in use:**
 - Cloud Run Java
 - Path to template

**Additional context**
This came up as we were testing the local development flow with IntelliJ. When using Skaffold and Jib as the builder, the tests will run as part of the build and the failing tests will cause the build to fail.

I noticed the test appear to rely on a server running on localhost, and they do indeed pass when I start the application locally before running the test suite, but that won't be the case when using the local development run configuration since that's how the user is starting the server. They can't start the server without running tests, and they can't run tests without starting the server.

The other Cloud Run samples have similar test suites that rely on local servers running as well. I found this a bit confusing myself, but I'd be interested in understanding the rationale and discussing it further. Let me know if I've misunderstood anything or can help in any way. 🙂

**Comment by etanshaul** [comment]
@simonz130 @grayside fyi. this would be a blocker.

**Comment by grayside** [comment]
Based on our design, the tests are all end-to-end tests which are executed by the cloudbuild.yaml pipeline and can be executed manually by first starting the service locally.

It sounds like the expectation outlined here is to run tests to validate the codebase before starting the service locally: what kind of testing is expected?

**Comment by etanshaul** [comment]
If they are not unit tests then they should not be run as part of the build. 

As mentioned by @fsladkey when using Jib to build to the Java sample, the tests are run and (of course) fail. This basically means that the user cannot use Jib with the Java sample without a bunch of friction (removing / rewriting / excluding the test). I suggest excluding the test from running during the build if the intention was as an end to end test.

**Comment by etanshaul** [comment]
friendly ping on this

**Comment by averikitsch** [comment]
Java test are tied to `mvn package`. However for Jib, you only need to compile first which skips the tests. Are we trying to circumvent the tests with Java or are we ripping out the E2E tests for all languages?

**Comment by etanshaul** [comment]
Hi @averikitsch . I think we have some options here.

1) Configure Jib to skip the tests, like we do in the Dockerfile for mvn. E.g.: `RUN mvn -Dmaven.test.skip=true package`
2) Rework the tests so that these unit tests are _not_ tied to mvn package. Typically end-to-end tests re run separately, not as part of the regular build. What the idea behind these for them to be run as part of the samples repo CI?

(1) is a short-term fix. It will solve the immediate issue but I don't think is a great long-term solution. For one, you have no way of adding actual unit tests into the project and having the run with the build (without getting rid of the e-to-e tests, or doing (2)).

**Comment by etanshaul** [comment]
Update - you wouldn't configure Jib to skip the tests. that's a maven config.

@fsladkey @matthewmichihara , I suppose running Skaffold with `--skip-tests` is the right thing to do now that I think about it more.

**Comment by fsladkey** [comment]
Alright then, I can make a PR for that.

**Comment by fsladkey** [comment]
> I think (2) above is a still a better long term solution.

+1!

**Comment by etanshaul** [comment]
Let's leave this open here to track the bigger effort of reworking the tests in the samples. @averikitsch does that sound ok?

**Comment by grayside** [comment]
Not sure I'm following the new goal here: if I understand, the longer-term goal is to have a way to run unit tests separate from e2e tests so we can have some of the test coverage built into more workflows.

We often do this in samples by requiring an environment variable to "activate" the e2e tests.

**Comment by etanshaul** [comment]
> Not sure I'm following the new goal here: if I understand, the longer-term goal is to have a way to run unit tests separate from e2e tests so we can have some of the test coverage built into more workflows.

Yes exactly. An env var could work. Another common pattern I've seen is to bind integration tests to a separate maven command (e.g. `./mvnw integrationTests`). This keeps it separate from the build, and allows us to add "real" unit tests to be run as part of the build.

**Comment by grayside** [comment]
Let's leave this targeted at the launch blocker and open a follow-up for later.

**Comment by averikitsch** [comment]
I've updated the sample ([PR](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/260)) where only unit tests run with `mvn package`. I've also want to delete the Dockerfile to stay consistent using jib.

**Comment by etanshaul** [comment]
@averikitsch thanks for the quick turnaround!

I think you can leave the Dockerfile. In Cloud Code, we allow the user to select their preferred builder. If we have a Dockerfile, they can choose to use that if they prefer.

**Comment by simonz130** [comment]
Now the tests pass. Closing the bug. Thanks, @averikitsch! 

```bash
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
