### ISSUE TITLE
[BUG] Go guestbook sample (sometimes) fails when running skaffold

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#258]
1) clone the Kubernetes Go guestbook sample application
2) (from the terminal) run `skaffold dev` (full command shown below). Sometimes the app starts. Sometimes the frontend fails with:
`querying backend failed: Get "http://go-guestbook-backend:8080/messages": dial tcp 10.122.5.65:8080: connect: connection refused`
and from the app logs:
```
[go-guestbook-frontend-7d64466946-wkcwv frontend] 2020/03/31 21:23:56 querying backend for entries
[go-guestbook-backend-6fb6656c5b-6jphr backend] 2020/03/31 21:23:59 ping to mongodb failed: context deadline exceeded
[go-guestbook-backend-6fb6656c5b-6jphr backend] 2020-03-31T21:23:59Z error layer=rpc writing response:write tcp [::1]:3000->[::1]:43740: use of closed network connection
```

Full skaffold command run:
```
skaffold dev --filename skaffold.yaml  --default-repo gcr.io/[replace_with_gcp_proj] --rpc-port 50051 --port-forward=true --status-check=true --enable-rpc=true
```

**Comment by etanshaul** [comment]
@simonz130 are you able to reproduce this?

**Comment by kelsk** [comment]
I'm able to reproduce this, looking into a fix.
