### ISSUE TITLE
[BUG] "numeric-project-id project-id" displays instead of project in Cloud Run sample

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#273]
**Describe the bug**
I see "_numeric-project-id project-id_" as the project on the website for a Cloud Run Hello World sample instead of showing the actual project value. 

**To Reproduce**
1. Create a Cloud Run NodeJS sample application in Cloud Code (Command Palette > New Application > Cloud Run > NodeJS Hello World) 
2. Click on Cloud Code on the taskbar and select Cloud Run: Deploy
3. Select Deploy
4. Once the deploy succeeds, click the URL to view the website

**Expected behavior**
The correct project value displays

**Screenshots**
![image](https://user-images.githubusercontent.com/1621731/78415114-87cb8500-75d4-11ea-90e6-4622b77bad6d.png)

**Template in use:**
 - NodeJS
 - Cloud Run Hello World 

**Cloud Code in use:**
 - Cloud Code for VS Code
 - OS: OSX
 - Browser: Chrome
 - Version: 80

**Additional context**

**Comment by kelsk** [comment]
Fixed by [#413](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/413)
