### ISSUE TITLE
`go-hello-world` sample not working

### ISSUE THREAD

**Issue by dgageot** [GoogleCloudPlatform/cloud-code-samples#28]
On Docker Desktop, whether I run it with the extension or `skaffold dev`, I'm unable to connect to `localhost:80`.

Here's the log:
```
[go-hello-world-5db5b95f55-h5hf8 server] API server listening at: [::]:3000
[go-hello-world-5db5b95f55-h5hf8 server] 2019-04-03T06:32:23Z info layer=debugger launching process with args: [/src/hello-world/debug]
```

If I comment out this line in the Dockerfile:

```
ENTRYPOINT ["dlv", "debug", "./cmd/hello-world",  "--api-version=2", "--headless", "--listen=:3000", "--log"]
```

and uncomment this one:
```
ENTRYPOINT ["/app"]
```

everything is fine.

I don't know if the debugger is just waiting for a connection or if something is not working. Anyways, this is not what I expect when I just want to deploy this sample.

**Comment by ahmetb** [comment]
This is expected. Currently dlv won’t start the process unlesss you attach the debugger. (Same for guestbook.)

That’s why the default entrypoint is not the debugger. Kubecode team is aware of this.

**Comment by ahmetb** [comment]
Ah looks like the default is left on dlv. I guess I accidentally added it in a commit.
