### ISSUE TITLE
[BUG] Clarify structure of readme for Cloud Run samples for target audience in the IDE

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#295]
**Describe the bug**
When I see the readme for a Cloud Run sample, I see the first section is Getting Started and the two bullets are saying to "Install Cloud Code for IntelliJ" and "Creating a new Cloud Run app". These bullets make sense if you are viewing this in the browser but don't make sense at all when viewing in the IDE since you have already installed the plugin and have already created the app which is the target audience for these

**To Reproduce**
1. Open IntelliJ with latest Cloud Code (pre-release with Cloud Run support)
2. Create a new project
3. Select Cloud Code > Cloud Run 
4. Enter a name and click create 
5. View the rendered readme.md that is displayed

**Expected behavior**
A clear message with the bullets at the top of the readme summarize the functionality that you should try out in the IDE now that you have this sample open already. In the IDE, I don't need to see how to install the plugin or create a new cloud run app because that's already done. If we want to keep this in the sample, move it to the bottom or have a quick note that people clearly understand to skip if in the IDE. 

The target audience is viewing these in the IDE with Cloud Code already installed so i'd move this section to the install/create to the bottom or something. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1621731/79139151-9fd89c80-7d6a-11ea-80ec-da31f4d1ba35.png)

**Template in use:**
 - Language: Java
 - Path to template: Cloud Run

**Cloud Code in use:**
 - Cloud Code for IntelliJ on IntelliJ 2020.1
 - OS: Mac
 - Browser: n/a
 - Version: n/a

**Additional context**

**Comment by simonz130** [comment]
Fixed in #293
