### ISSUE TITLE
[BUG] Remove local dev instructions for Cloud Run samples 

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#296]
**Describe the bug**
Remove the instructions to run cloud run apps locally for now

**To Reproduce**
1. Open IntelliJ with latest Cloud Code (pre-release with Cloud Run support)
2. Create a new project
3. Select Cloud Code > Cloud Run 
4. Enter a name and click create 
5. View the rendered readme.md that is displayed

**Expected behavior**
No instructions for local dev

**Screenshots**
https://screenshot.googleplex.com/h3V0reWYiDn.png

**Template in use:**
 - Language: Java
 - Path to template: Cloud Run 

**Cloud Code in use:**
 - Cloud Code for IntelliJ on IntelliJ 2020.1
 - OS: Mac
 - Browser: n/a
 - Version: n/a

**Additional context**

**Comment by simonz130** [comment]
This is fixed in #293
