### ISSUE TITLE
[BUG] java-guestbook sample is broken

### ISSUE THREAD

**Issue by matthewmichihara** [GoogleCloudPlatform/cloud-code-samples#353]
https://paste.googleplex.com/5987088744841216

**Comment by etanshaul** [comment]
@simonz130 could we look at this asap?

**Comment by matthewmichihara** [comment]
It looks like it is related to this change:  https://github.com/renovate-bot/cloud-code-samples/commit/e6f3cc3a62556effbe8d26f3122d19b33f0364c7

Reverting `org.springframework.boot:spring-boot-starter-parent` from `2.3.0.RELEASE` to `2.1.4.RELEASE` fixed the issue.
