### ISSUE TITLE
Sample assumes `GOOGLE_CLOUD_PROJECT` is set, which is not the case in Cloud Run

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-code-samples#367]
https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/1e2e58446c08c8e7fd0a9f3253f926e560bf5514/nodejs/nodejs-cloud-run-hello-world/index.js#L14

if needed, the project ID should be fetched from the instance metadata server, which is exposed by all GCP Compute products.

Also, it's unclear why the samples need to display the project ID. What's the goal?

CC @grayside

**Comment by kelsk** [comment]
It doesn't seem valuable to display the project ID, since the user has already specified their project ID when they deployed the sample.

I'll remove the project ID in the next sample update.

**Comment by kelsk** [comment]
Fixed w/ #582
