### ISSUE TITLE
cloudbuild.yaml in Cloud Code samples have an unintended teardown step

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-code-samples#372]
1. In Cloud Code, Create a new Node.js Cloud Run app.
2. a `cloudbuild.yaml` file is created along the source code.

**Expected:**

This `cloudbuild.yaml` helps me build and deploy my cloud run app using Cloud Build. It should be directly usable in a Cloud Build Trigger to set up Continuous Deployment.

**Observed:**

The `cloudbuild.yaml`  contains a ["teardown" step](https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/nodejs/nodejs-cloud-run-hello-world/cloudbuild.yaml#L56) which deletes the deployed service. 
This file seems more to be a file we (google) use to test the sample code than what we would really recommend developers to do.

CC @grayside

**Comment by simonz130** [comment]
This file needs to be deleted - we moved it to .ci folder that is 1 level higher up than the sample.

**Comment by steren** [comment]
Thanks. That makes sense.
