### ISSUE TITLE
[BUG] Guestbook apps are missing README files

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#386]
For example, the java guestbook app.

**Comment by quoctruong** [comment]
This is related to https://github.com/GoogleCloudPlatform/cloud-code-vscode-internal/issues/2752 in VSCode.

**Comment by kelsk** [comment]
This is fixed in the pending README update.
Updating this bug to P2, will close when README merge is complete

**Comment by kelsk** [comment]
Fixed with #568
