### ISSUE TITLE
[BUG] Lack of guidance in readme.md for Hello World K8s sample 

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#390]
**Describe the bug**
It would be helpful for the readme.md to contain a brief explanation of the key files in the sample such as the service.yaml, deployment.yaml, app.js, skaffold.yaml, launch.json for vscode, Dockerfile and what role they play in making this sample work. 

**To Reproduce**
1. Open VS Code with Cloud Code
2. "New Application" -> "Kubernetes Application" -> "NodeJS Hello World" 

**Expected behavior**
A clear description of what the sample is in the readme.md before getting to next steps. 

**Screenshots**
![image](https://user-images.githubusercontent.com/1621731/88599500-c45a3b00-d020-11ea-9111-7b6e496fd2b2.png)

**Template in use:**
 - NodeJS Hello World for K8s

**Cloud Code in use:**
 - [Cloud Code for VS Code]

**Comment by etanshaul** [comment]
copying over a plan discussed in a comment on a friction log (https://docs.google.com/document/d/19wnth7w75IxmSEGIi_BokLumtw8HX0szD4a6Nwgf0bA/edit?disco=AAAAKFJPSFk&usp_dm=true&ts=5f31d4a0) to help resolve this:

> Wanted to also point out a discussion I had with @chairy@google.com today about this topic:

> She suggested an interesting idea of splitting out the READMEs into 3 separate versions:

> - the "normal" README.md which is what you'd expect to see when viewing the samples right on GitHub. This sort of matches what we have today - no assumptions about which platform they may be using. Having actions like "Download IntelliJ" which make no sense right now when the user already is using IntelliJ, would apply for this case.
> - An intellij README (README_INTELLIJ.md, or something similar)
> - A VS Code README (README_VSCODE.md, or something similar)

> The last two could then be much better targeted for the platform (and would assume the user arrived at them from within our Samples integration). The IDEs would be responsible for auto-opening the correct one.

**Comment by kelsk** [comment]
A list of explanations is planned to add to the next README update.
Updating this bug to P2, will close when README merge is complete

**Comment by kelsk** [comment]
Fixed with #568
