### ISSUE TITLE
Validation error in VS Code in hello.deployment.yaml when creating NodeJS K8s Hello World template

### ISSUE THREAD

**Issue by russwolf** [GoogleCloudPlatform/cloud-code-samples#394]
**Repro Steps:** 
1. Create a new K8s NodeJS Hello World application in VS Code
2. Expand **kubernetes-manifests** and select **hello.deployment.yaml** (may require waiting a little or switching between files for LSP to catch up I guess?)

**Expected:** 
**hello.deployment.yaml** contains no schema validation errors 

**Actual:** 
**hello.deployment.yaml** appears to contain schema errors since lines 20-29 have yellow squiggly underlines. I don't know what's wrong...?
After hovering over line 28, I was eventually able to see this message "One or more containers do not have resource limits - this could starve other processes" which I assume is why there is the yellow underline?

![image](https://user-images.githubusercontent.com/1621731/88949986-d9b1ae00-d248-11ea-8f5e-28d657616165.png)

**Comment by vincentjocodes** [comment]
I cannot repro

**Comment by kelsk** [comment]
Closing this issue due to inability to repro
