### ISSUE TITLE
[BUG] .net core attach ,localRoot not work

### ISSUE THREAD

**Issue by nocanstillbb** [GoogleCloudPlatform/cloud-code-samples#399]
**Describe the bug**
not matter i set `localRoot` what, vs code aways popup a window which rightBottom tell me "\src\src\myproject\program.cs" not found  when i operated attached my pod and pressed pause button ,  untill i copied my project folder to `c:\src\src`   
`thread /stack/local var `  debug window is ok when this bug happend  
this is my launch.json content  
```
        {
            "name": "Attach to Kubernetes Pod (.NET Core)",
            "type": "cloudcode.kubernetes",
            "request": "attach",
            "language": "NETCore",
            "podSelector": {
                "app": "hscadaexblazor"
            },
            "localRoot": "${workspaceFolder}",
            "remoteRoot": "/app"
        }
```

**To Reproduce**
1. Go to 'debug module'
2. Click on 'Attach to Kubernetes Pod (.NET Core)'  json content see `Describe the bug` 
3. select my .net core  process to attach
4.click pause button
5. See error

**Expected behavior**
not matter i set `localRoot` what, vs code aways popup a window which rightBottom tell me "\src\src\myproject\program.cs" not found  when i operated attached my pod and pressed pause button ,  untill i copied my project folder to `c:\src\src`   
`thread /stack/local var `  debug window is ok when this bug happend  

**Screenshots**
![image](https://user-images.githubusercontent.com/22405678/89118630-a0dc3800-d4d9-11ea-99d7-9e890a9a9cc6.png)

** Template in use:**
 - Language zh-cn
 - Path to template

**Cloud Code in use:**
 - [Cloud Code for VS Code] 
 - OS: win10 64bit  1809
 - Browser  chorme
 - Version  latest

**Additional context**

**Comment by kelsk** [comment]
Hi @nocanstillbb, are you still having this issue with the Kubernetes Pod debugger, with the latest version of Cloud Code (v1.8.0)?
