### ISSUE TITLE
[BUG] Improve READEMEs across the samples

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#404]
The READMEs need some work. This has been ongoing feedback for quite some time.

This is an umbrella issue to cover the overall effort around fixing the READMEs across the samples. This includes items like:

- Adding in missing READMEs for the guestbook apps (https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/386)
- Having more actionable steps (https://github.com/GoogleCloudPlatform/cloud-code-samples/issues/390)
- Providing relevant information (e.g. the architectural diagram takes up a lot of space).

A nice example of friction:
https://docs.google.com/document/d/19wnth7w75IxmSEGIi_BokLumtw8HX0szD4a6Nwgf0bA/edit?ts=5f30f9e2

**Comment by etanshaul** [comment]
copying over a plan discussed in a comment on a friction log (https://docs.google.com/document/d/19wnth7w75IxmSEGIi_BokLumtw8HX0szD4a6Nwgf0bA/edit?disco=AAAAKFJPSFk&usp_dm=true&ts=5f31d4a0) to help resolve this:

> Wanted to also point out a discussion I had with @chairy@google.com today about this topic:

> She suggested an interesting idea of splitting out the READMEs into 3 separate versions:

> - the "normal" README.md which is what you'd expect to see when viewing the samples right on GitHub. This sort of matches what we have today - no assumptions about which platform they may be using. Having actions like "Download IntelliJ" which make no sense right now when the user already is using IntelliJ, would apply for this case.
> - An intellij README (README_INTELLIJ.md, or something similar)
> - A VS Code README (README_VSCODE.md, or something similar)

> The last two could then be much better targeted for the platform (and would assume the user arrived at them from within our Samples integration). The IDEs would be responsible for auto-opening the correct one.

**Comment by kelsk** [comment]
This is fixed in the pending README update.
Updating this bug to P2, will close when README merge is complete

**Comment by kelsk** [comment]
Fixed with #568
