### ISSUE TITLE
Idea - add a comment in skaffold.yaml files with links to skaffold docs for users that are curious

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#405]
idea from @russwolf 's friction log:
https://docs.google.com/document/d/19wnth7w75IxmSEGIi_BokLumtw8HX0szD4a6Nwgf0bA/edit?ts=5f30f9e2

Users that clone the samples and open skaffold.yaml may want to be educated on what this config file does. A nice addition could be to have a comment in the configs explaining what this file is with links to the Skaffold docs.

**Comment by kelsk** [comment]
fixed with #539
