### ISSUE TITLE
README architecture diagrams overwhelm the readme and general not useful

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#408]
This is feedback from multiple friction logs now. Users weren't sure what to do with or how to interpret the architecture diagram. And more critically, some didn't scroll down to see the actual content (with links to docs etc.)

**Comment by kelsk** [comment]
#528 - Moving the diagrams to the end of the docs temporarily until they are reconstructed (or removed entirely).
