### ISSUE TITLE
Update to django 3.1 breaks guestbook app

### ISSUE THREAD

**Issue by kschaab** [GoogleCloudPlatform/cloud-code-samples#417]
**Describe the bug**
Commit `09a72cee6d01608dde3cf514a4b7037a0181fa5d` clearly failed triggers but was committed to master anyway.  This change introduces a break in the sample where the front end does not connect to the DB.

**To Reproduce**
Deploy Django guestbook app and load front end

**Screenshots**
![image](https://user-images.githubusercontent.com/7329029/90463019-d75fa880-e0be-11ea-975d-44ed25c5e8a7.png)

** Template in use:**
 - Language: Python Django
 - Path to template: python/django/python-guestbook

**Cloud Code in use:**
 - Cloud Code for VS Code
 - OS: Darwin
 - Browser Chrome
 - Version 1.5.0 RC

**Comment by simonz130** [comment]
This is the commit for reference: https://github.com/GoogleCloudPlatform/cloud-code-samples/commit/09a72cee6d01608dde3cf514a4b7037a0181fa5d#diff-4b53cd107182a2e32c74bc6c35070d1d

And this is the PR:
https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/374/checks

It's weird - the PR [did pass the checks](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/374/checks) but the history shows as if the checks didn't run.

@kelsk - can you please investigate?

**Comment by kelsk** [comment]
I made a second commit [b3e5183](https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/374/commits/b3e5183d633475a27d96558d91097a922e4cef9c) to merge `master` into the PR. Then, the checks ran successfully.

I'll need some guidance if this was the wrong procedure.

I'll revert the commit.

**Comment by kschaab** [comment]
I think we saw that it was intermittent, can you try more than once?

**Comment by kschaab** [comment]
There is a race here for the repro.  Originally it looked like it was caused by django update because rolling back fixed the issue.  However, at that point we had several failures and no successes and it didn't look like a race condition.  Later on another person was able to deploy successfully and then redeployed and got the failure so then it looked like a race.  It is possible that due to the circumstances it is not caused by the update, just saw the update as the only significant change between failure and success.

**Comment by donmccasland** [comment]
priority: p0 is for when the code should be rolled back, is effecting many customers.

**Comment by donmccasland** [comment]
Attempting to repro

**Comment by donmccasland** [comment]
Deployed 8 times, can not repro
