### ISSUE TITLE
Add support for deploying Ruby on Rails

### ISSUE THREAD

**Issue by MarkBennett** [GoogleCloudPlatform/cloud-code-samples#43]
As a Ruby developer, I expect this to deploy Ruby on Rails apps, given how popular the RoR framework is.

**Comment by MarkBennett** [comment]
Great work on this project and perfect timing as I'm just learning how to deploy to kubernetes!

**Comment by simonz130** [comment]
Thanks for the feedback, Mark. We will consider Ruby sample.

**Comment by MarkBennett** [comment]
I can't commit to anything for the next few weeks, but you'd you be open to a PR @simonz130?

**Comment by simonz130** [comment]
Yeah, totally. We welcome contributions.

**Comment by MarkBennett** [comment]
Awesome! I've just been doing a bunch of work to setup Rails app with dev and production profiles using `skaffold` & `kustomize`. I'll blog about it soon, but I'm thinking it might integrate well with this.

**Comment by emanzx** [comment]
+1 for RoR

**Comment by Shabirmean** [comment]
Closing it since there is no short-term commitment to support RoR. Feel free link issue with contributions.
