### ISSUE TITLE
django example please

### ISSUE THREAD

**Issue by ekimia** [GoogleCloudPlatform/cloud-code-samples#44]
Would be a great addition!

**Comment by simonz130** [comment]
Thanks Evan, we will consider that.

**Comment by simonz130** [comment]
Good news: it's on the way: https://github.com/GoogleCloudPlatform/cloud-code-samples/pull/59

**Comment by simonz130** [comment]
It's finally live!
https://github.com/GoogleCloudPlatform/cloud-code-samples/commit/30b631a9de56e652db1d0f78f49b908cb7be6999
