### ISSUE TITLE
Java examples should provide a Jib builder (as a profile)

### ISSUE THREAD

**Issue by ivanporty** [GoogleCloudPlatform/cloud-code-samples#48]
Many Java developers opt to use Jib as a default image builder for their project and integration with Skaffold is first-class. While we can keep Dockerfile based profile as a default, having a custom Jib based profile and examples of using Jib with modules for `guestbook` project is very valuable.

**Comment by patflynn** [comment]
ping.  Would a PR to do this be accepted?

**Comment by simonz130** [comment]
Yeah, we accept contributions. I recommend adding an option to use jib but this should not be the only option (docker should still be supported)
