### ISSUE TITLE
alt not an attribute of source element

### ISSUE THREAD

**Issue by abbycar** [GoogleCloudPlatform/cloud-code-samples#508]
**Describe the bug**
In the hello world samples html files, there's a `source` element with an `alt` attribute.
`alt` isn't a [supported attribute for source](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source).

Example:
https://github.com/GoogleCloudPlatform/cloud-code-samples/blob/master/python/python-hello-world/src/templates/index.html#L148

**Comment by kelsk** [comment]
Fixed with #515
