### ISSUE TITLE
Suggestion - enable squash merging

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#53]
Currently, when merging a PR, all commits from the feature branch are merged onto master. This imo creates a messy history on master. If you enable squash merging, then each feature (PR) gets squashed into a single commit, with no merge commits.

<img width="776" alt="Screen Shot 2019-04-26 at 10 10 40 AM" src="https://user-images.githubusercontent.com/1735744/56813817-ccb73b00-680b-11e9-90a6-6c88d395722b.png">

This is a matter a of taste, so just take this as a suggestion.

**Comment by iantalarico** [comment]
+1 to squash merge. I agree it makes history and tracking much cleaner

**Comment by simonz130** [comment]
I was about to enable it but it's already seems enabled.
![image](https://user-images.githubusercontent.com/32641282/57735258-d38ddc80-7658-11e9-8c83-410ce0a83029.png)
Therefore, closing. LMK if you can't use it for some reason.

**Comment by etanshaul** [comment]
Thanks. I don’t have merge privileges. I just noticed a messy commit history before. Perhaps it was just recently enabled; or maybe people were just not using the feature.

**Comment by etanshaul** [comment]
Oh I see, you may want to also uncheck both “allow merge commits” and “allow rebase merging”. But it really depends on what workflow you want.

**Comment by simonz130** [comment]
Yeah, we are working on setting CI/CD pipeline for this repo.
