### ISSUE TITLE
“project” template variable in the Cloud Run python sample displays as “Unavailable” when run in emulator

### ISSUE THREAD

**Issue by j-windsor** [GoogleCloudPlatform/cloud-code-samples#583]
**From friction log:** https://docs.google.com/document/d/120SdyZa78VRGbMtPptM-qRnVWqlp7kZoSHkA1PF0ABY/edit#

**Describe issue:** The “project” template variable in the Cloud Run python sample displays as “Unavailable” when run locally. It works when deployed to managed. Users might think something is wrong with this messaging. [Bookmark](https://docs.google.com/document/d/120SdyZa78VRGbMtPptM-qRnVWqlp7kZoSHkA1PF0ABY/edit#bookmark=id.a5bbmt47mzxp)

**Applicable screen shots:**
<img width="747" alt="Screen Shot 2020-10-23 at 3 50 09 PM" src="https://user-images.githubusercontent.com/4994906/97199358-284de600-176d-11eb-85c8-b22bfb3d4345.png">

**Comment by kelsk** [comment]
Fixed with #582
