### ISSUE TITLE
Django guestbook does not work with skaffold dev watch mode

### ISSUE THREAD

**Issue by j-windsor** [GoogleCloudPlatform/cloud-code-samples#612]
We have a k8s Job running `django migrate` based on the frontend image. When I am in skaffold dev in watch mode, and I update a file in the frontend, skaffold detects the change, rebuilds the frontend image, updates the k8s manifests, deploys, and errors out every time. This is because skaffold is updating the spec.containers field in the Job manifest, which is an immutable field.

**Comment by j-windsor** [comment]
Relevant issues:
- I filed a bug on skaffold for this here: https://github.com/GoogleContainerTools/skaffold/issues/5513
- We could eventually change this to use these to do it in a less hacky way (because whatever we do to fix now this will be hacky): https://github.com/GoogleContainerTools/skaffold/issues/1441

**Comment by kelsk** [comment]
To solve this issue for now, we'll add the `--force` flag to the skaffold kubernetes manifests.

This will result in a slightly slower redeploy time, but the app won't break in `watch` mode.
