### ISSUE TITLE
Reduce startup time for Java samples

### ISSUE THREAD

**Issue by kelsk** [GoogleCloudPlatform/cloud-code-samples#621]
The Java language samples have overly long build times that can be upwards of 4 minutes. 

The samples should be refactored to reduce startup time as much as possible.

**Comment by averikitsch** [comment]
* Cloud Run: The entire build averages 2.5 mins with 1 min being integration tests
* Hello World and Guestbook: Deploy to staging is the longest averages 2.5min with the build is only 30-40s, polling for endpoint can also be an issue.

The main issue is the amount of time for the K8s deployment to become stable. The build is quick and there is not currently any optimization or refactoring for the app's start up time. Up to @kelsk to close or keep open.

**Comment by ace-n** [comment]
#101 may help here

**Comment by ace-n** [comment]
Pinged @kelsk who said this is good to close.
