### ISSUE TITLE
SpringBoot packaging error showin in logs while trying to Skaffold Run the Java sample

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/cloud-code-samples#69]
`
Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage (repackage) on project hello-world: Execution repackage of goal org.springframework.boot:spring-boot-maven-plugin:2.1.2.RELEASE:repackage failed: Unable to find main class -> [Help 1]
`

**Comment by patflynn** [comment]
I was able to fix this by adding `<start-class>cloudcode.helloworld.HelloWorldApplication</start-class>` to properties in pom.xml, but I'm confused as to why SpringBoot is having trouble since I can only see one main class in the source.

**Comment by simonz130** [comment]
Just to confirm - are you trying helloWorld sample only? Does it happen in guestbook sample for java?

**Comment by patflynn** [comment]
yeah, I'm running skaffold dev from the hello-world directory.

**Comment by patflynn** [comment]
haven't tried the guestbook

**Comment by patflynn** [comment]
just checked, and the guestbook does seem to have the same error.

**Comment by askmeegs** [comment]
Hello, sorry for the delay on this. I have tried to build the latest `java-hello-world` and `java-guestbook` to reproduce your error, but my builds succeed. 

Generating tags...
 - java-hello-world -> gcr.io/megan-fall20/java-hello-world/java-hello-world:latest
Checking cache...
 - java-hello-world: Not found. Building
Building [java-hello-world]...
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------< org.springframework.boot:hello-world >----------------
[INFO] Building Cloud Code Hello World 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jib-maven-plugin:2.4.0:_skaffold-fail-if-jib-out-of-date (default-cli) @ hello-world ---
[INFO]
[INFO] ----------------< org.springframework.boot:hello-world >----------------
[INFO] Building Cloud Code Hello World 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-maven-plugin/2.1.4.RELEASE/spring-boot-maven-plugin-2.1.4.RELEASE.pom
....
[INFO] --- jib-maven-plugin:2.4.0:build (default-cli) @ hello-world ---
[WARNING] 'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}
[INFO]
[INFO] Containerizing application to gcr.io/megan-fall20/java-hello-world/java-hello-world...
[WARNING] Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
[INFO] Getting manifest for base image gcr.io/distroless/java:8...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Using base image with digest: sha256:90596f62a8ec0701d00845b85dfccf7f53b5e0bb3c49e275d7f19ea6c3e4565d
[INFO] Using credentials from Docker config (/Users/mokeefe/.docker/config.json) for gcr.io/megan-fall20/java-hello-world/java-hello-world
[INFO]
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, cloudcode.helloworld.HelloWorldApplication]
[INFO]
[INFO] Built and pushed image as gcr.io/REDACTED/java-hello-world/java-hello-world
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

I **do** see a warning - `'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}` so it's possible that a `main`-related check used to be an ERROR in your `spring-boot-maven-plugin` version (`2.1.2`) is now a WARNING in the latest version on master (`2.1.4`).  

I'm going to close this issue, feel free to reopen if you continue seeing build errors - if that's the case, please share what version of skaffold and Maven you have, along with the full error logs. Thank you!
