### ISSUE TITLE
Guestbook .md links don't work in IntelliJ

### ISSUE THREAD

**Issue by kelsk** [GoogleCloudPlatform/cloud-code-samples#799]
When opening the Cloud Code Java Guestbook sample in IntelliJ, the links in the table of contents do not work.

Since the links work in VS Code but not IntelliJ, it's likely that there's a formatting issue that needs to be resolved to render the README markdown correctly in IntelliJ, and the other samples' READMEs likely have this same issue in IntelliJ.

**Cloud Code in use:**
 - [Cloud Code for IntelliJ]
 - OS: macOS
 - Version 21.7.1

**Comment by briandealwis** [comment]
Seems to be a known issue:
- https://youtrack.jetbrains.com/issue/IDEA-213085
- https://youtrack.jetbrains.com/issue/IDEA-214326
- https://youtrack.jetbrains.com/issue/IDEA-238096
