### ISSUE TITLE
Debug Knative serving service - not just K8s Service

### ISSUE THREAD

**Issue by JCzz** [GoogleCloudPlatform/cloud-code-samples#843]
Cloud Code
`21.10.1`

skaffold version
`v1.31.0`

Goland
`2021.2`

The Kubernetes sample provided is for K8s service, is it possible to run other manifest like a Knative Serving service - I am asking as the following does not work using a Knative Service?

K8s Service
```
apiVersion: v1
kind: Service
metadata:
  name: go-hello-world
```

Knative Service
```
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-hello-world

```

**Comment by wietsevenema** [comment]
Cloud Code relies on `skaffold debug` which doesn't support debugging of knative services yet. For reference: https://github.com/GoogleContainerTools/skaffold/issues/4702
