### ISSUE TITLE
Java Guestbook (with skaffold modules) broken Maven configuration

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/cloud-code-samples#883]
1) Load the updated Java Guestbook app (modularized with skaffold modules)
2) Sync with maven (typically the IDE shows a little notification at the bottom)

Expected:
It works, and the maven structure is loaded

Actual:
Fails with
```
'parent.relativePath' of POM org.springframework.boot:backend:1.0 (/Users/eshaul/IdeaProjects/untitled691/backend/pom.xml) points at com.cloudcode.guestbook:java-guestbook instead of org.springframework.boot:spring-boot-starter-parent, please verify your project structure
```
<img width="1798" alt="Screen Shot 2021-11-05 at 11 17 29 AM" src="https://user-images.githubusercontent.com/1735744/140534596-9f51d636-d478-4a73-afb3-60e4945d7471.png">

Note: Cloud Code Intell'J deploy workflows still work, but its not the best experience for the users to see this error.

**Comment by ivanporty** [comment]
Fixed by #884
