### ISSUE TITLE
quota exceeded error when building the code

### ISSUE THREAD

**Issue by simonz130** [GoogleCloudPlatform/cloud-code-samples#95]
When building guestbook for go, we got this error:
```
Step #3 - "go tests": Step #1 - "deploy to staging": time="2019-09-23T22:59:28Z" level=fatal msg="failed to build: build failed: build failed: building [gcr.io/cloud-code-samples/guestbook-backend]: getting build status: googleapi: Error 429: Quota exceeded for quota metric 'cloudbuild.googleapis.com/get_requests' and limit 'GetRequestsPerMinutePerProject' of service 'cloudbuild.googleapis.com' for consumer 'project_number:296929634055'., rateLimitExceeded"
```

Full details here: https://pantheon.corp.google.com/cloud-build/builds/553d21d7-6db6-44fa-a03e-0ea60ed2ae30;step=3?project=cloud-code-samples

**Comment by murog** [comment]
Other PRs have passed and the repo is currently building successfully.  I wonder if the issue came about because two PR's were started in the same window.

**Comment by simonz130** [comment]
Possibly, but we need to be ready for this scenario

**Comment by simonz130** [comment]
I fixed the quota issues.
